### ISSUE TITLE
Rename the default branch from 'master' to 'main'

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/Modulated_Structures#9]
This potential reasons for renaming the branch are provide in issue https://github.com/COMCIFS/comcifs.github.io/issues/11.

It is probably safe to outright rename the branch as it does not seem to be cloned by anyone (except me, but I am fine with updating things on my end). it seems, that any outstanding PRs are automatically updated.

**Comment by jamesrhester** [comment]
This has now been done. Please update your local forks accordingly.
